# Funding information for Promptise
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: # GitHub Sponsors username (if applicable)
patreon: # Patreon username (if applicable)
open_collective: # Open Collective username (if applicable)
ko_fi: # Ko-fi username (if applicable)
custom: # Custom sponsor URL
