site_name: DeepMCPAgent
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
plugins:
  - search
  - mkdocs-click
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
  - click:
      module: deepmcpagent.cli
      command: app

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Server Specs & Auth: server-specs.md
  - Model Setup: model-setup.md
  - CLI: cli.md
  - Examples: examples.md
  - API: api.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Changelog: changelog.md
